### ISSUE TITLE
Logo Link Embedding

### ISSUE THREAD

**Issue by kaushalvivek** [kaushalvivek/megathon#10]
Sponsorship Logos need to be linked to respective companies.

**Comment by zubairabid** [comment]
Other than the Title Sponsor and Associate Sponsors everything is already linked (not including the Organising/Ecosystem Partners). I've added those and changed some stuff so that clicking on sponsor  links directly opens them on a new tab. Is that fine?

**Comment by kaushalvivek** [comment]
Hi @zubairabid , will get back to you by tonight, have my mids.

**Comment by kaushalvivek** [comment]
@zubairabid, create a pull request with the changes you have made, link the issue number.
