### ISSUE TITLE
Add Mail Links

### ISSUE THREAD

**Issue by kaushalvivek** [kaushalvivek/megathon#20]
Change the text of E-Cell IIT Hyderabad and E-Cell IIIT Hyderabad emails added at the bottom of the page to email links. (use mailto)

**Comment by sarvesh211999** [comment]
I am taking care of this issue

Sarvesh

**Comment by mridulnagpal** [comment]
I am working on this too.

**Comment by ishitavohra** [comment]
I'll take up this issue.

**Comment by kaushalvivek** [comment]
Fixed.
