### ISSUE TITLE
Update All Sponsors for 2017

### ISSUE THREAD

**Issue by kaushalvivek** [kaushalvivek/megathon#30]
We have the info for that now. I'll comment the new structure in a while.

**Comment by KunalSerum123** [comment]
taken

**Comment by KunalSerum123** [comment]
I'm taking care of this issue.

**Comment by kaushalvivek** [comment]
TItle Sponsor - Amazon
Assosciate Title Sponsor - CapGemini
Knowledge Partner - PwC
Challenge Sponsor - IBM
Social Responsibility Partner- She Team Hyd Police
Exclusive Ticketing Partner - Mera Events
Technology Partner - Digital Ocean & .tech
Outreach Partner - StuMagz
Event Partner - AugustFest and TechFest

New List.
Remove all other Sponsors, let Venue Partner, Food Partner, Investors stay.

**Comment by kaushalvivek** [comment]
Fixed it on my own due to urgency.
